In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn import svm, datasets
from sklearn import metrics
from sklearn.model_selection import StratifiedKFold
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis as QDA
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn import neighbors

In [10]:
mat = pd.read_csv('pcs.csv', sep = " ").values
mat

array([[-4.20796672e+01, -4.41809060e+01, -8.23556405e+00,
        -2.10610171e+01,  5.92628638e+00,  1.74256176e+01],
       [-7.95082426e+00, -2.52315172e+01,  3.82024221e+01,
         2.21613053e+01, -3.72148192e+01, -4.51981820e+01],
       [-5.78174453e+01,  1.64446497e+01, -1.74964240e+01,
        -7.30154682e+01,  3.51776209e+01, -5.15688615e+00],
       [ 3.20046386e+01, -6.11477251e+01,  1.40598729e+01,
         1.35143043e+02,  3.70153008e+01, -4.75693907e+00],
       [-1.08689107e+02, -5.44398554e-01, -5.10658159e+01,
        -9.54904683e+00,  1.90864948e+01,  1.55254352e+01],
       [-8.29255031e+01,  3.71793240e+00, -3.63794163e+01,
         2.83623102e+01, -4.22677720e+01,  1.18424602e+01],
       [-3.91851614e+01, -3.39056363e+01, -2.53781315e+01,
        -2.42956651e+01, -1.05155089e+02, -1.78773513e+01],
       [-2.68794225e+01, -3.72554989e+01,  2.80122351e+01,
         3.52848051e+01,  3.51707704e+01,  3.11212989e+01],
       [ 1.11019753e+00, -9.49093016e+01,  3.417

In [11]:
random_state = np.random.RandomState(0)
cv = StratifiedKFold(n_splits=5)
classifier = neighbors.KNeighborsClassifier(6)
y = np.concatenate((np.ones(22), np.zeros(21))) #actual class labels (cases: 0-22, controls: 23-42)

aucs = []
for i, (train, test) in enumerate(cv.split(mat, y)):
    ypred = classifier.fit(mat[train], y[train]).predict(mat[test])
    fpr, tpr, thresholds = metrics.roc_curve(y[test], ypred, pos_label=1)
    aucs.append(metrics.auc(fpr, tpr))
print(np.mean(aucs))

0.875


In [12]:
classifier = svm.SVC(kernel='linear')
X = list(map(float, "1.6880367 1.3761867 1.4387857 1.2358717 1.6663818 1.7164176 1.4356663 1.4896716 1.4273986 1.5295093 1.9050754 1.6545259 1.5417555 1.0901908 1.2457502 1.4991921 1.4298004 1.3956367 1.5438028 1.4636095 1.0000000 1.0000000 1.3144254 1.1627663 0.8731719 0.6733056 0.8708223 0.8515857 1.4914607 1.2799251 0.9160978 0.7803538 0.6643310 0.7698050 0.7254972 0.6521681 0.7162422 0.9242445 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000".split(" ")))
X = np.array(X).reshape(-1, 1)
aucs = []
for i, (train, test) in enumerate(cv.split(X, y)):
    ypred = classifier.fit(X[train], y[train]).predict(X[test])
    fpr, tpr, thresholds = metrics.roc_curve(y[test], ypred, pos_label=1)
    aucs.append(metrics.auc(fpr, tpr))
print(np.mean(aucs))

0.835


In [14]:
mat2 = pd.read_csv('pcsOUT.csv', sep = " ").values #predicting outside samples (ppl with asthma, asthma+nasal polyps)
classifier = neighbors.KNeighborsClassifier(6)
classifier.fit(mat, y)
ypred = classifier.predict(mat2)
print(ypred)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 1.]


In [15]:
classifier = svm.SVC(kernel='linear')
classifier.fit(mat, y)
ypred = classifier.predict(mat2)
print(ypred)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1.]


In [16]:
classifier = GaussianNB()
classifier.fit(mat, y)
ypred = classifier.predict(mat2)
print(ypred)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1.]
